package com.zhaowq.leetcode;

/**
 * Find the Difference
 * <p>
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * <p>
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 *
 * @author zhaowq
 * @date 2018/12/25
 */
public class Solution389 {

    /**
     * 此处为笨办法，看discuss是用异或。
     */
    public char findTheDifference(String s, String t) {
        int[] sCount = new int[26];
        for (char c : s.toCharArray()) {
            sCount[c - 97] = sCount[c - 97] + 1;
        }

        int[] tCount = new int[26];
        for (char c : t.toCharArray()) {
            tCount[c - 97] = tCount[c - 97] + 1;
        }

        for (int i = 0; i < 26; i++) {
            if (sCount[i] != tCount[i]) {
                return (char) (i + 97);
            }
        }
        return 'a';
    }
}
